Create SECURITY.md
jboss-msc/jboss-msc pull request #100
Opened 2022-11-04 15:18 UTC by ronsigal

2022-11-08 21:31 UTC, dmlloyd commented on SECURITY.md
> +<PROJECT_NAME> community takes security very seriously, and we aim to take immediate action to address serious security-related problems that involve our products or services.
```suggestion
The JBoss community takes security very seriously, and we aim to take immediate action to address serious security-related problems that involve our products or services.
```

Keep it simple/general? I'm not great at things like this 😅

2023-03-02 14:41 UTC, rhusar requested changes

2023-03-02 14:41 UTC, rhusar commented on SECURITY.md
> +https://access.redhat.com/security/team/contact
Needs a new line above this one to render properly.

2023-10-02 09:39 UTC, ropalka commented
This PR is already obsolete - it was resolved via https://github.com/jboss-msc/jboss-msc/commit/0c472386d5ba0f5c7a55d7f4172199ff7d94d0fd

2023-10-02 09:39 UTC, closed without merging